name: Docker Build CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        id: docker_build
        run: |
          docker build -t grade-calculator .
          echo "BUILD_STATUS=success" >> $GITHUB_ENV

      - name: Print success message
        if: steps.docker_build.outputs.BUILD_STATUS == 'success'
        run: echo "✅ Docker build test passed!"

  build-selfhosted:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push selfhosted image
        id: docker_build_push_selfhosted
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/grade-calculator:${GITHUB_SHA} -f selfhosting/Dockerfile .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/grade-calculator:${GITHUB_SHA}
          echo "BUILD_STATUS=success" >> $GITHUB_ENV

      - name: Print success message
        if: steps.docker_build_push_selfhosted.outputs.BUILD_STATUS == 'success'
        run: echo "✅ Selfhosted image built and pushed to Docker Hub"
