name: Tag Docker Image on Git Tag

on:
  push:
    tags:
      - "*"

jobs:
  tag-docker-image:
    runs-on: golang:alpine
    env:
      REGISTRY: docker.atlas.nstr.dev
      IMAGE_NAME: grade-calculator

    steps:
      - name: Install crane
        run: |
          apk add --no-cache git && go install github.com/google/go-containerregistry/cmd/crane@latest

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get commit SHA for tag
        id: get_sha
        run: |
          COMMIT_SHA=$(git rev-list -n 1 $GITHUB_REF_NAME)
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
          echo "Resolved git tag $GITHUB_REF_NAME to commit SHA $COMMIT_SHA"

      - name: Crane Login
        run: |
          crane auth login $REGISTRY --username $USERNAME --password $TOKEN

      - name: Wait for image to exist
        run: |
          echo "Waiting for image $REGISTRY/$IMAGE_NAME:${COMMIT_SHA} to be available..."
          until crane manifest $REGISTRY/$IMAGE_NAME:${COMMIT_SHA}; do
            echo "Not available yet... waiting 5s"
            sleep 5
          done
          echo "Image is now available!"

      - name: Copy image to git tag
        run: |
          echo "Copying $REGISTRY/$IMAGE_NAME:${COMMIT_SHA} to $REGISTRY/$IMAGE_NAME:${GITHUB_REF_NAME}"
          crane copy $REGISTRY/$IMAGE_NAME:${COMMIT_SHA} $REGISTRY/$IMAGE_NAME:${GITHUB_REF_NAME}

      - name: Done
        run: echo "Tagging completed successfully."
